import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Minecraft WikiNote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <h1>
          Minecraft Millinote
        </h1>
        <div className="divider" />
        <div className="grid">
        <Link href="/java">
          <div className="card card-compact w-96 bg-base-100 shadow-xl">
          <figure><img src="https://api.lorem.space/image/shoes?w=400&h=225" alt="Shoes" /></figure>
          <div className="card-body">
            <h2 className="card-title">Java Edition</h2>
            <p>If a dog chews shoes whose shoes does he choose?</p>
            <div className="card-actions justify-end">
              <button className="btn btn-primary">Let&apos;s go!</button>
            </div>
          </div>
          </div>
        </Link>
        
        <Link href="/be">
          <div className="card card-compact w-96 bg-base-100 shadow-xl">
          <figure><img src="https://api.lorem.space/image/shoes?w=400&h=225" alt="Shoes" /></figure>
          <div className="card-body">
            <h2 className="card-title">Bedrock Edition</h2>
            <p>If a dog chews shoes whose shoes does he choose?</p>
            <div className="card-actions justify-end">
              <button className="btn btn-primary">Let&apos;s go!</button>
            </div>
          </div>
          </div>
        </Link>
        </div>
      </>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
